version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/new-probation-services
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: Flow check
          command: yarn flow-check
      - run:
          name: Unit test
          command: yarn test
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: ~/new-probation-services
          paths:
            - build
  deploy-job:
      docker:
        - image: circleci/node:8.9.4
      steps:
        - run:
            name: Install awscli
            command: |
              sudo apt install python-pip python-dev
              sudo pip install awscli
        - attach_workspace:
            at: ~/new-probation-services
        - run:
            name: Deploy to AWS
            command: aws s3 sync ~/new-probation-services/dist/ s3://moj-studio.dnt.prototype2 --acl public-read --sse AES256 --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
